#spring:
#  main:
#    allow-bean-definition-overriding: true # for config error
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/brave?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: qwer1234

spring:
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/brave
    username: brave
    password: 1234

  # spring data jpa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

# swagger ??
springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha # ?? ??
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

#logging:
#  level:
#    sql: info